# Use
This notebook will be used to tests the functions of the python files

In [1]:
import numpy as np
import warnings
%load_ext autoreload
%autoreload 2
from hungarian import preprocess, alternate, hungarian

## Test of `preprocess(C)`

In [2]:
n=4
C = np.random.random(size=(n,n))
n,U,V,row,x = preprocess(C)
print(C-U[:,np.newaxis]-V,"\n",x)

[[0.12399937 0.05994744 0.         0.29650315]
 [0.         0.         0.30128235 0.09388995]
 [0.48262015 0.3016672  0.15835949 0.        ]
 [0.         0.36591536 0.68839674 0.1281276 ]] 
 [[False False  True False]
 [ True False False False]
 [False False False  True]
 [False False False False]]


In [3]:
# Exemple 4.3
n=4
C = np.array([[7,9,8,9],
              [2,8,5,7],
              [1,6,6,9],
              [3,6,2,2]])
n,U,V,row,x = preprocess(C)
print(C-U[:,np.newaxis] - V, row, U, V,"\n", x)

[[0 0 1 2]
 [0 4 3 5]
 [0 3 5 8]
 [1 2 0 0]] [0 None 3 None] [7 2 1 2] [0 2 0 0] 
 [[ True False False False]
 [False False False False]
 [False False False False]
 [False False  True False]]


seem ok
- The zero entries match the True entries
- Internal assertions satisfied
- Same results as exemple 4.3
## Test of `alternate(C,U,V,row,k)`

In [4]:
n=4
C = np.random.randint(10,size=(n,n))
n,U,V,row,x = preprocess(C)
print(row)
k=0
assert not(row[k] is None), "Invalid candidate k"
sink,pred,SU,LV = alternate(C,U,V,row,k)
print(sink,pred,SU,LV)
print(C-U[:,np.newaxis]-V)

[0 2 3 1]
0
  0
  1
0
2
None [0 0 None None] [ True False  True False] [ True  True False False]
[[0 0 1 7]
 [4 2 3 0]
 [9 0 2 8]
 [5 7 0 0]]


In [5]:
# Exemple 4.3
n=4
C = np.array([[7,9,8,9],
              [2,8,6,7],
              [1,6,6,9],
              [3,6,2,2]])
n,U,V,row,x = preprocess(C)
k=1
sink,pred,SU,LV = alternate(C,U,V,row,k)
print(sink,pred)

1
  0
0
  1
1 [1 0 None None]


## Tests of `hungarian(C)`

In [6]:
# Exemple 4.3
n=4
C = np.array([[7,9,8,9],
              [2,8,6,7],
              [1,6,6,9],
              [3,6,2,2]])
row,phi,U,V = hungarian(C)

k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1
k= 1


KeyboardInterrupt: 

## Questions/remarks
- We must test the **scalar equality** $u_i+v_j=c_{ij}$ multiple times, for now done with a tolerance of proximity but it's not very absolute and strong. How resolve? Solutions:
    - Use integers by **rescaling**.(the more we rescale the slower it becomes)
    - During the dual updating, **save the index** where the constrain is becoming active (by saving the argmin, see how to do it)
    
    -> it is indeed true with tolerance but wont affect the convergence of the algorithm neither the final output significantly

- implementation of **sets** by **vectors**. Better by python sets?

    -> we'll see, not so bad 

- describe the functionment of algorithm? a sketch of background?

    -> yes, sketch the idea, describe the steps, invariants, stopping situation.