# Use
This notebook will be used to tests the functions of the python files

In [229]:
import numpy as np
import warnings
%load_ext autoreload
%autoreload 2
from hungarian import preprocess, alternate, hungarian

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Test of `preprocess(C)`

In [230]:
n=4
C = np.random.random(size=(n,n))
n,U,V,row,x = preprocess(C)
print(C-U[:,np.newaxis]-V,"\n",x)

[[0.04099524 0.71312632 0.         0.        ]
 [0.13421323 0.         0.31843028 0.97785158]
 [0.09460212 0.         0.15851638 0.41010239]
 [0.         0.3728614  0.050814   0.32254943]] 
 [[False False  True False]
 [False  True False False]
 [False False False False]
 [ True False False False]]


In [231]:
# Exemple 4.3
n=4
C = np.array([[7,9,8,9],
              [2,8,5,7],
              [1,6,6,9],
              [3,6,2,2]])
n,U,V,row,x = preprocess(C)
print(C-U[:,np.newaxis] - V, row, U, V,"\n", x)

[[0 0 1 2]
 [0 4 3 5]
 [0 3 5 8]
 [1 2 0 0]] [0 None 3 None] [7 2 1 2] [0 2 0 0] 
 [[ True False False False]
 [False False False False]
 [False False False False]
 [False False  True False]]


seem ok
- The zero entries match the True entries
- Internal assertions satisfied
- Same results as exemple 4.3
## Test of `alternate(C,U,V,row,k)`

In [232]:
n=4
C = np.random.randint(10,size=(n,n))
n,U,V,row,x = preprocess(C)
k=n-1
if np.any(row==k):
     print("Invalid candidate k, try again")
else:
    sink,pred,SU,LV = alternate(C,U,V,row,k)
    print(row)
    print(sink,pred,SU,LV)
    print(C-U[:,np.newaxis]-V)

Invalid candidate k, try again


In [233]:
# Exemple 4.3
n=4
C = np.array([[7,9,8,9],
              [2,8,6,7],
              [1,6,6,9],
              [3,6,2,2]])
n,U,V,row,x = preprocess(C)
k=1
sink,pred,SU,LV = alternate(C,U,V,row,k)
print(sink,pred)

1 [1 0 None None]


## Tests of `hungarian(C)`

In [234]:
# Exemple 4.3
n=4
C = np.array([[7,9,8,9],
              [2,8,6,7],
              [1,6,6,9],
              [3,6,2,2]])
row,x,phi,U,V = hungarian(C)
print(row,phi,U,V)
print(1*x)

hungarian succed (feasibility and complementary slackness holds)
[2 0 1 3] [1 2 0 3] [8 6 5 2] [-4  1  0  0]
[[0 1 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]]


In [275]:
# random integer
n=10
C = np.random.randint(0,10,(n,n))
row,x,phi,U,V = hungarian(C)
print(row,phi,U,V)
print(1*x)

hungarian succed (feasibility and complementary slackness holds)
[1 3 5 9 4 2 8 7 6 0] [9 0 5 1 4 2 8 7 6 3] [0 1 0 0 0 4 1 2 1 2] [-1  1  0 -1  1  0  0  0 -1  0]
[[0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]]


In [261]:
# random gaussian
n=4
C = np.random.random(size=(n,n))
row,x,phi,U,V = hungarian(C)
print(C)
print(C-U[:,np.newaxis]-V)
print(row,phi,U,V)
print(1*x)

hungarian succed (feasibility and complementary slackness holds)
[[0.19089889 0.36030293 0.4244699  0.40219438]
 [0.73102179 0.62626495 0.1425945  0.62521685]
 [0.63197301 0.58546574 0.84839769 0.62939854]
 [0.64763894 0.67083242 0.24680277 0.53797185]]
[[0.         0.16940404 0.48080729 0.16736269]
 [0.34119102 0.23643417 0.         0.19145327]
 [0.04650728 0.         0.51016823 0.        ]
 [0.15359989 0.17679337 0.         0.        ]]
[0 2 1 3] [0 2 1 3] [0.19089889 0.38983078 0.58546574 0.49403905] [ 0.          0.         -0.24723628  0.04393281]
[[1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]]


## Questions/remarks
- We must test the **scalar equality** $u_i+v_j=c_{ij}$ multiple times, for now done with a tolerance of proximity but it's not very absolute and strong. How resolve? Solutions:
    - Use integers by **rescaling**.(the more we rescale the slower it becomes)
    - During the dual updating, **save the index** where the constrain is becoming active (by saving the argmin, see how to do it)
    
    -> it is indeed true with tolerance but wont affect the convergence of the algorithm neither the final output significantly

- implementation of **sets** by **vectors**. Better by python sets?

    -> we'll see, not so bad 

- describe the functionment of algorithm? a sketch of background?

    -> yes, sketch the idea, describe the steps, invariants, stopping situation.