# Use
This notebook will be used to tests the functions of the python files

In [1]:
import numpy as np
%load_ext autoreload
%autoreload 2
from hungarian import preprocess,alternate

In [14]:
n=4
C = np.array([[0.55035163, 0.82187454, 0.98519958, 0.58755737],
 [0.21229879, 0.01152798, 0.07833661, 0.74777171],
 [0.4747819,  0.5093062,  0.35526866, 0.23517837],
 [0.9345975,  0.49134766, 0.00118716, 0.57445652]])
 # np.random.random(size=(n,n))
n,U,V,row,x = preprocess(C)
print(C-U[:,np.newaxis]-V,"\n",x)

[[0.         0.27152291 0.43484795 0.03720574]
 [0.20077081 0.         0.06680863 0.73624373]
 [0.23960353 0.27412783 0.12009029 0.        ]
 [0.93341034 0.4901605  0.         0.57326936]] 
 [[ True False False False]
 [False  True False False]
 [False False False  True]
 [False False  True False]]


Ok, the zero entries match the True entries.